# 默认非裁剪地图配置 (标准全图载入，无物理裁切)
crop_box:
  enable: false                     # 显式关闭空间裁剪，载入全图

# 标准流形拓扑图参数
sor_mean_k: 0                     # 流形图同步关闭离群滤波
min_cluster_points: 1             # 单柱 1 个点即可提取踏面

